[build-system]
requires = ["maturin>=1.0"]
build-backend = "maturin"

[project]
name = "rusty_orbital_dynamics"
version = "0.1.0"
description = "High-performance orbital dynamics in Rust + Python"
authors = [{name = "Jacob Sorensen", email = "sorensenjacob44@gmail.com"}]
